/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_ftw_salb_TTSEngine_nativeSynthesize */

#ifndef _Included_HTSTTS
#define _Included_HTSTTS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_ftw_speechsynthesis_TTSEngine
 * Method:    nativeSynthesize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jshortArray JNICALL Java_at_ftw_salb_TTSEngine_nativeSynthesize
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
